### ISSUE TITLE
To do list.

### ISSUE THREAD

**Issue by justin-p** [AD4Noobs/site#2]
Things that need to be covered in the basic version:

- [x] What is AD and why is it used (#3)
- [x] How to create an AD (#6)
- What are/is:
  - [x] Objects/Attributes/Classes/Containers/Leafs and Schema
  - [x] Domain, site, tree, forest
  - [x] Functional Levels
  - [x] Global Catalog
  - [x] FSMO
  - [x] RODC
  - [x] NTDS
  - [x] SYSVOL
- [x] Active Directory and computers (#15)
  - [x] AD Recycle bin
  - [x] OU's
  - [x] Different Objects
	- [x] Default Objects (builtin groups for example)
	- [x] Security Principals
    	- [x] Users
    	- [x] Computers
    	- [x] Groups
	- [x] Searching in AD
  - [x] Add PC to domain
- [ ] File server (#20)
  - [X] Security Descriptors
  - [x] Company Share
    - [x] Access Based Enum
    - [x] Basic List R/RW share setup with groups
- [ ] GPOs
  - [ ] Add company share
  - [ ] Set IE home page
  - [ ] Change Password Policy
- [ ] Adding a second DC
- [ ] DNS
  - [ ] forwarders vs Roothints
  - [ ] Reverse lookup zone
  - [ ] Logging
  - [ ] Aging and Scavenging
  - [ ] What NOT to do

Things that should be covered in the basic version:

- [ ] Sites and services
- [ ] Some interactive exercises 

Things that are nice to have in the Basic version:

- [ ] DHCP role
- [ ] User Profile
- [ ] Password Polices
- [ ] Account lockout
- [ ] Kerberos Policy
- [ ] user rights assignments
- [ ] Windows Firewall
- [ ] more offensive side:
  - [ ] SPN
  - [ ] GPO with passwords
  - [ ] Password in netlogon
  - [ ] Passwords in AD Attributes
  - [ ] Default Firewall and why its important

**Comment by justin-p** [comment]
moved to PR

**Comment by justin-p** [comment]
Moved back to issue since PR is getting merged.
